version: "3"

services:

  nginx:
    image: nginx:1.23.0
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
    depends_on:
      - api_service
    ports:
      - "80:80"

  api_service:
    build: ./api_service
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./docker/pg-variables.env

  postgres:
    image: postgres:14.4
    restart: always
    env_file:
      - ./docker/pg-variables.env